trigger:
- master

stages:

# -----------------------------
# Stage 1: Build
# -----------------------------
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'   # Use Linux agent here
    steps:
    - task: Maven@4
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
        goals: 'package'

    - task: CopyFiles@2
      displayName: 'Copy WAR files to artifact staging directory'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**/*.war'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish WAR artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'warfile'
        publishLocation: 'Container'

# -----------------------------
# Stage 2: Deploy to Azure
# -----------------------------
- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  dependsOn: Build
  jobs:
  - deployment: DeployToQA
    environment: 'QA'
    pool:
      vmImage: 'ubuntu-latest'    # Linux agent for deployment
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: warfile

          - task: AzureWebApp@1
            displayName: 'Deploy .war to Azure Web App'
            inputs:
              azureSubscription: 'MyAzureConnection'  # Your service connection name
              appType: 'webApp'
              appName: 'venudemo'                      # Your Azure Web App name
              package: '$(Pipeline.Workspace)/warfile/**/*.war'

# -----------------------------
# Stage 3: QA Tests (Selenium + TestNG)
# -----------------------------
- stage: QA
  displayName: 'Run Selenium TestNG QA Tests'
  dependsOn: Deploy
  jobs:
  - job: RunSeleniumTests
    pool:
      vmImage: 'ubuntu-latest'   # Linux agent for tests
    steps:
    - task: Maven@4
      displayName: 'Run Selenium TestNG Tests'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'test'
        options: '-Dsurefire.suiteXmlFiles=testng.xml'   # your TestNG suite XML
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'

    - task: PublishTestResults@2
      displayName: 'Publish Selenium TestNG Test Results'
      inputs:
        testResultsFiles: '**/target/surefire-reports/TEST-*.xml'  # Default pattern for TestNG results
        testRunTitle: 'Selenium TestNG Test Results'
      condition: succeededOrFailed()  # Publish results even if tests fail
